### ISSUE TITLE
Typing into date inputs types only on the yyyy section.

### ISSUE THREAD

**Issue by ric2b** [checkly/headless-recorder#100]
Trying to record typing into a date field doesn't work for me, it just types on the `yyyy` section of the date and ends up completely invalid.

What I've had work really well was replacing `await page.type(selector, '2020-08-07');` with:

```javascript
await page.focus(selector);
await page.keyboard.type('20200807');
```

Would it be within scope of the extension to recognize date inputs and use this alternative instead?

**Comment by tnolet** [comment]
@ric2b thanks for mentioning. I would gladly take a PR that implements this.

**Comment by noahsnowc** [comment]
Just checking, but since its been several months, is this still open?

**Comment by maxigimenez** [comment]
Hi @noahsnowc, yes, this is still an open issue.

**Comment by ianaya89** [comment]
@ric2b @noahsnowc Hi, we are trying to get back on this. 
I am testing this issue and could not reproduce it.
When I click the input and I type (or manually select a date), the value is properly generated.

![Kapture 2021-01-11 at 16 01 26](https://user-images.githubusercontent.com/3258966/104226750-0d634780-5427-11eb-99dc-3210436a5c03.gif)


Am I missing something? If so, can you provide more information/details on this?

**Comment by ric2b** [comment]
@ianaya89 The recording looks ok, it captures the whole date, but when I replay only the `yyyy` section is modified, at least on the test form I'm using which is [this Google Form](https://docs.google.com/forms/d/e/1FAIpQLSeaN9V4DdW5L0VV4eYlvIEDtj2-Hh6u3xEVNSXyYsa2NeWGMQ/viewform).

**Comment by p-o-p-oCat** [comment]
looks great
though My chrome just went corrupted qwq

**Comment by ianaya89** [comment]
https://github.com/checkly/headless-recorder/issues/232
