### ISSUE TITLE
`page.select` should be `page.selectOption` on playwright

### ISSUE THREAD

**Issue by raguiar2** [checkly/headless-recorder#104]
Playwright's API does not have a `select` method for page. Instead, it is called `selectOption`. This is not captured in the headless recorder, and should be refactored accordingly, otherwise playwright flows will not work with select dropdowns, as it will record the event as `page.select` which is undefined and throws an error.

**Comment by tnolet** [comment]
@raguiar2 thanks for catching that! We will create a fix for this! Tagging @maxigimenez
