### ISSUE TITLE
Can no longer access iframes

### ISSUE THREAD

**Issue by jamieni** [checkly/headless-recorder#106]
Because of the removal of ` "permissions": ["*://*/"]` in `manifest.json`, the extension can no longer access iframes.

**Comment by maxigimenez** [comment]
Thanks for reporting this @jamieni. 
Can you describe in what scenario are you hitting this issue? I just try it here https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select and I'm able to generate code using the DOM of the iframe on the right.

**Comment by jamieni** [comment]
Hi @maxigimenez, the scenario is when the iframe has a different base url than the original url. 
i.e. original url: abc.com iframe url: abc-def.com

**Comment by maxigimenez** [comment]
Thanks for the clarification @jamieni, just tested your PR, and looks good
