### ISSUE TITLE
Dark Mode 🕶!

### ISSUE THREAD

**Issue by krryptonian** [checkly/headless-recorder#112]
This is **greate extension**. 🎉 But now a day the **dark mode** is on trends.

**Comment by tnolet** [comment]
Hi @krryptonian thanks for the props! Greatly appreciated. I think a dark mode is not really on the table anytime soon or anytime at all. We have much bigger fish to fry before we go into visual design tweak. That's why I'm closing this issue.

**Comment by ianaya89** [comment]
Done
