### ISSUE TITLE
Please who can help me

### ISSUE THREAD

**Issue by maikShoe** [checkly/headless-recorder#113]
radio input, is active by default and a window should appear as in the picture if it is active!

[Screenshot_2020-10-18-18-51-38-843_com.android.browser.jpg](https://user-images.githubusercontent.com/73071142/96373150-41560600-1173-11eb-990a-7577cea47f24.jpg)

**Comment by maxigimenez** [comment]
Hi @maikShoe, can you provide more information about how to reproduce the issue?

**Comment by maxigimenez** [comment]
Closing for lack of information
