### ISSUE TITLE
integrate headless-recorder with my own code

### ISSUE THREAD

**Issue by yael118** [checkly/headless-recorder#115]
Hi,
First of all thanks for the cool tool you have created

I wanted to know if the project shown here can be run on my PC or is it just a major part of the chrome extension code
Because I want to perfect functions customized to me.
For example converting the command "click" when it appears in a specific class routing to my personal function that will record a number of other actions besides a click in this case.

**Comment by maxigimenez** [comment]
Hi @yael118! I'm glad to know that 😃 . 
Yes, you can run the project locally following the steps on the README.md and do as many changes as you want in your own version.

**Comment by yael118** [comment]
Thanks for your response!
But i followed the instruction on README.md and i don't have the build package in my local project 
 in Development instructions:
![צילום מסך 2020-11-01 102720](https://user-images.githubusercontent.com/64949819/97798319-c0e0dc00-1c2d-11eb-8569-c9c14e4d2f0d.png)

**Comment by maxigimenez** [comment]
Are you getting any error after running `npm run dev`? Because this script will generate the build folder where you need to point the extension to.

**Comment by maxigimenez** [comment]
Are you getting any error after running `npm run dev`? Because this script will generate the build folder where you need to point the extension to.
