### ISSUE TITLE
Can't record action in iframe webpage

### ISSUE THREAD

**Issue by bryanzhou** [checkly/headless-recorder#142]
### Env
Release 1.0.0-beta.4
8b6eff5

### Q1
Recorder shows duplicate code ,like this:
```
  await page.waitForSelector('.ibox-content > .clients-list > .nav > li:nth-child(3) > a')
  await page.click('.ibox-content > .clients-list > .nav > li:nth-child(3) > a')
  
  await page.waitForSelector('.ibox-content > .clients-list > .nav > li:nth-child(3) > a')
  await page.click('.ibox-content > .clients-list > .nav > li:nth-child(3) > a')
  
  await page.waitForSelector('#tauth_submit')
  await page.click('#tauth_submit')
  
  await page.waitForSelector('#tauth_submit')
  await page.click('#tauth_submit')
```
### Q2
I can't record action in iframe webpage,but I'm not sure weather it's a bug or my mistake in operation.

**Comment by ianaya89** [comment]
@bryanzhou thanks for reporting. 
Do you have more information to reproduce this? The website you are using or whatever information will help.

I Will take a look.

**Comment by bryanzhou** [comment]
> @bryanzhou thanks for reporting.
> Do you have more information to reproduce this? The website you are using or whatever information will help.
> 
> Will take a look.

Thanks for your reply. I tried to update chrome and build extension on master branch today, and Q1 is sloved. 
The website of Q2 is on Weibo.com , [link](https://weibo.com/manage/frame?furl=https%3A%2F%2Fweibo.com%2Fl%2Fwblive%2Fadmin%2Fhome%2Fliveadmin&to=create) .it's a console board ,needs registion and identity authentication, so I toke a screenshot and attached below
![image](https://user-images.githubusercontent.com/7711142/126292147-e368e457-e871-47d6-9651-89e17c648d72.png)

**Comment by ianaya89** [comment]
@bryanzhou right now I made a technical choice of disabling iframe recording.
The reason is related to the new overlay control bar added to the recorder. 
I am looking for a workaround and alternatives to allow iframe again. 
Will keep you updated!

**Comment by bryanzhou** [comment]
Got it!Thanks a lot!

**Comment by ianaya89** [comment]
https://github.com/checkly/headless-recorder/issues/232
