### ISSUE TITLE
Toggle or Relocate Play Bar

### ISSUE THREAD

**Issue by script2mylou** [checkly/headless-recorder#144]
The play bar at the bottom of the recorded screen obstructs an element I need to access.  Is it possible to relocate or toggle on/off the play bar?

**Comment by ianaya89** [comment]
@script2mylou thanks for submitting this. 
Toggle functionality is on the roadmap and will be added soon

**Comment by ianaya89** [comment]
Still needs some design tweaks but this is how it will look

![hr](https://user-images.githubusercontent.com/3258966/126832750-2b1897f8-1b83-4b11-893e-595a1a13119a.gif)
