### ISSUE TITLE
A few feedbacks about TAB usage

### ISSUE THREAD

**Issue by yusufozturk** [checkly/headless-recorder#146]
Hi,

I was doing some tests and I would like to share my feedbacks:

1. First of all, tab is not working at all. But weirdly it was able to capture one or two input areas.
2. UX is not letting you to see flow of the events. So basically you need to stop recording and then you are lucky enough to see if it was able to capture your typing or not. If UX would allow you to see events in realtime, you can see that it didn't capture the typing, so you can continue to keep pressing tab button.
3. Usage of tab is confusing. There are many issues just about it. I think it's proven that it's not user friendly. Because it's not natural. When you want to create flow tests, you just click and type inputs like how you usually do. You don't press extra keys or you don't correct the text. So just record whatever is typed. If user would like to correct the text, they can correct it later. But if you don't record anything at all, there is no chance to do any modification later.

Feel free to accept it as feedback or ignore it.

PS: Cypress recorder was successful to capture typings right about 90-95% of the tests. Even if there is extra typing, I was able to remove it by clicking "X" on that event in their UI. When the typing was truncated, I was able to modify it later. Also drag and drop support for event sorting was very helpful. Their UI is very bad, but when it comes to usability they do the job well. So for now, we will recommend that one to our customers.

**Comment by ianaya89** [comment]
Thanks for the feedback, we will take it in mind for our next release.

**Comment by ianaya89** [comment]
https://github.com/checkly/headless-recorder/issues/232
