### ISSUE TITLE
The file "Browser-extension" is not working ,after cloning this repo in github.

### ISSUE THREAD

**Issue by aasim-syed** [checkly/headless-recorder#150]
I wanted to improve the aesthetic look of this website, the HTML is not opening.

![image](https://user-images.githubusercontent.com/70385414/129921391-df993a55-6b69-40cf-802f-866beed8c1c8.png)

**Comment by ianaya89** [comment]
Hi @aasim-syed, the extension is built with Vue.js and static edition/usage will not work.

You have to install dependencies and run the app using dev mode:

1. `npm i` (install)
2. `npm run serve` (run)

You can find more details on README file.
https://github.com/checkly/headless-recorder#%EF%B8%8F-run-locally
