### ISSUE TITLE
UI truncated when default chrome zoom is more than 100%

### ISSUE THREAD

**Issue by rizrmd** [checkly/headless-recorder#161]
With default zoom at chrome setting is set more than 100%, headless recorder UI is truncted: 

> 
![image](https://user-images.githubusercontent.com/126301/133425492-6d1237fd-438b-4515-bddd-a3e64f5efdfd.png)

**Comment by ianaya89** [comment]
Thanks for reporting, we will review it.

**Comment by ianaya89** [comment]
Hi @rizkyramadhan, I am not able to reproduce this. 
I tried zooming in/out but UI does not scale with browser zoom. Can you bring more info or steps to reproduce the issue?
![hr](https://user-images.githubusercontent.com/3258966/134687852-fac50fc0-7a11-4f30-b7db-a05f71698e5a.gif)

**Comment by rizkyramadhan** [comment]
![image](https://user-images.githubusercontent.com/126301/134758746-af8af2b3-ec3c-4d2f-b1e7-982344f5cf39.png)

You have to change default zoom on chrome settings page

**Comment by ianaya89** [comment]
https://github.com/checkly/headless-recorder/issues/232
