### ISSUE TITLE
Default to text selectors for Playwright

### ISSUE THREAD

**Issue by RyKilleen** [checkly/headless-recorder#167]
Is it technically feasible to default to something like `button:has-text("Log In")` instead of incredibly long, unmaintainable selectors? Some way of defaulting to the shortest text-based selector when possible? I'd love to be able to use this extension while also following Playwright's best practices of using text in all possible cases.

**Comment by dolfje** [comment]
With pull request https://github.com/checkly/headless-recorder/pull/178 it is possible to set a custom resolver. In the pull request, you can also find code that you have to set as custom resolver

**Comment by mex511511mno** [comment]
I

**Comment by mex511511mno** [comment]
The

**Comment by ianaya89** [comment]
https://github.com/checkly/headless-recorder/issues/232
