### ISSUE TITLE
add option to use ARIA nth model ?

### ISSUE THREAD

**Issue by hugodlmm** [checkly/headless-recorder#186]
I wanted to record instagram input but I find that every class name are random values.
So here is my question, is it possible to add an option to record with ARIA nth model ?
e.g : 
```
await page.waitForSelector('body > section > div:nth-child(2) >  div:nth-child(1) > button)
await page.click('body > section > div:nth-child(2) >  div:nth-child(1) > button)
```
instead of : 
```
await page.waitForSelector('body > .RnEpo > .pbNvD > ._1XyCr > .bIiDR')
await page.click('body > .RnEpo > .pbNvD > ._1XyCr > .bIiDR')
```

**Comment by ianaya89** [comment]
@hugodlmm thanks for reporting. We are currently doing a re-work in our selectors engine and it will work with a similar approach you propose. Will keep you updated.

**Comment by ianaya89** [comment]
https://github.com/checkly/headless-recorder/issues/232
