### ISSUE TITLE
Chrome extension manifest V3 

### ISSUE THREAD

**Issue by IRE-vs** [checkly/headless-recorder#210]
Thank you for your extension, it helps a lot to record tests for playwright.

Do you plan to migrate with the new manifest version 3?

[Manifest V2](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/)

**Comment by ianaya89** [comment]
Hi @IRE-vs, thanks for pointing this out. We will plan manifest migration to fit the support line.

**Comment by ianaya89** [comment]
https://github.com/checkly/headless-recorder/issues/232
