### ISSUE TITLE
Crypto wallet integration for dapp e2e tests

### ISSUE THREAD

**Issue by ivelin** [checkly/headless-recorder#213]
Hi checkly, team. Congrats for continuing to innovate with a great product.

Have you been able to look at integrating interactions with crypto wallet Chrome extensions such as MetaMask? It would help a great deal improving UX for web3 apps.

Possibly through integration with dappetter?
https://github.com/sriharikapu/dappetter

Related blog post with more context:
https://mirror.xyz/jjpa.eth/Nt6oojn6WcnmDzV97CL1XFGXkNkyWekAGaCEO5SYpXE

There is a parallel discussion with wallet and browser providers:
https://community.brave.com/t/e2e-testing-for-web3-app-interactions-with-brave-wallet/318181/6

Thank you,

Ivelin

**Comment by ianaya89** [comment]
Hi @ivelin, thanks for your question. We don't have any plan for this soon but looks quite interesting, we will keep it on our radar.

**Comment by ivelin** [comment]
Any updates on adding ability to test web3 apps via chrome extensions like metamask? Maybe via [dappeteer](https://github.com/decentraland/dappeteer)

**Comment by ianaya89** [comment]
hey @ivelin, is still in consideration but not in our roadmap (for now). Sorry I don't have better news at the moment

**Comment by ivelin** [comment]
> hey @ivelin, is still in consideration but not in our roadmap (for now). Sorry I don't have better news at the moment

Thank you for the prompt  response, @ianaya89 . I will keep an eye out for future updates. In the meantime, we are able to get some of this done with `Synpress`, a Cypress extension for web3.

https://user-images.githubusercontent.com/2234901/184508838-e5aefa05-8b3f-4121-9c4b-160d93a78bc2.mp4

Project source repo here:
https://github.com/ivelin/sweat-token/tree/fix-pm-gas-v2/e2e-tests

**Comment by ianaya89** [comment]
https://github.com/checkly/headless-recorder/issues/232
