### ISSUE TITLE
Generated code readability and reusability improvement

### ISSUE THREAD

**Issue by vanetreg** [checkly/headless-recorder#224]
I have an improvement suggestion regarding generated codes:
instead of using repeatedly codes like:
```
await page.waitForSelector('veryLongStringRepeated');
await page.click('veryLongStringRepeated');
```
something like:
```
let activeSelector = 'veryLongStringRepeated';
waitForAndClickActiveSelector(activeSelector);
```
would improve code reusability and readability.

**Comment by ASISBusiness** [comment]
> I have an improvement suggestion regarding generated codes:
> 
> instead of using repeatedly codes like:
> 
> ```
> 
> await page.waitForSelector(veryLongStringRepeated);
> 
> await page.click(veryLongStringRepeated);
> 
> ```
> 
> something like:
> 
> ```
> 
> activeSelector = 'veryLongStringRepeated;
> 
> waitForAndClickActiveSelector(activeSelector);
> 
> ```
> 
> would improve code reusability and readability.
> 
> 
> 
>

**Comment by ianaya89** [comment]
https://github.com/checkly/headless-recorder/issues/232
