### ISSUE TITLE
Trust uniqueness of `id`s if present

### ISSUE THREAD

**Issue by ephetic** [checkly/headless-recorder#60]
Puppeteer-recorder has a special case for using a shorter selector if the target element has an `id`, but why not just use the `id` alone?

Likewise, if a long selector contains any `id`s, why not drop the whole prefix up to the last `id`?

**Comment by ianaya89** [comment]
The problem I see with this is when an element has an `id` and `data-` attribute and the user enables `data-` attribute setting.
 I think in that scenario `data-*` must take precedence over the `id`
