### ISSUE TITLE
Drag & Drop support

### ISSUE THREAD

**Issue by honsa** [checkly/headless-recorder#71]
Nice usefull extension, thank you for all the effort.

What is about drag&drop support?

I know this is not easy, but have you planed to implement it?

I stay tuned, happy to see this project grows from day to day 👍

**Comment by tnolet** [comment]
@honsa no planning for this yet, but it makes sense to add. I'll label it!

**Comment by tnolet** [comment]
@honsa please have a look at https://github.com/checkly/puppeteer-recorder/issues/83 as we are picking up development again.

**Comment by ianaya89** [comment]
https://github.com/checkly/headless-recorder/issues/232
