### ISSUE TITLE
Record 'copy' and 'paste' keystrokes?

### ISSUE THREAD

**Issue by alexiskattan** [checkly/headless-recorder#80]
There is a piece of data that i want to copy from one location in a webpage and paste it into an input field.  [ctrl] + [something] keystrokes though aren't recorded.  Is there a way to add this to the plugin?

**Comment by TwoLeaves** [comment]
Would love this. Can't quite find anything like this extension, as bare as it is.

**Comment by tnolet** [comment]
@alexiskattan can you give an extensive example of what you mean? Hitting CTRL+C & CTRL+V is certainly possible to record, but the difficulty comes from what is actually saved and where it is pasted. We would need to also track cursor position or mouse position and many other things.

**Comment by tnolet** [comment]
Please also have a look at https://github.com/checkly/puppeteer-recorder/issues/83

**Comment by ianaya89** [comment]
https://github.com/checkly/headless-recorder/issues/232
