### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by digitarald** [checkly/headless-recorder#89]
Firefox team member here. Since Puppeteer already has experimental support for Firefox, I'd love to help to get this extension working as well.

I suspect that it only takes minimal effort to make this extension work in Firefox and to submit it to Firefox's addon site: https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/ . If it turns out to be harder, I'd be happy to help with specifics.

**Comment by tnolet** [comment]
Hi @digitarald that sounds great. Would love to enable Puppeteer Recorder for the Firefox community. 

Could you give me an idea of what tweaks we would need?

**Comment by digitarald** [comment]
@tnolet auditing the CRX file in https://www.extensiontest.com/test/2bd86bf0-b57b-11ea-8f8c-ef9090840f8d only mentions one API (which can probably use [runtime.onConnect](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onConnect)).

The page I linked also guides you to submit to Firefox's addons. The docs I linked explain side-loading as well so you can do a try-run.

**Comment by tnolet** [comment]
@digitarald I would gladly take a PR for this. Otherwise we probably do not have the bandwidth to go after this.

**Comment by ianaya89** [comment]
With the latest version of HR we are close to getting compatibility with Firefox. 
Can't promise a date yet but this is on the radar.

**Comment by ianaya89** [comment]
https://github.com/checkly/headless-recorder/issues/232
