### ISSUE TITLE
recording halts/crashes on some pages/interactions

### ISSUE THREAD

**Issue by YoraiLevi** [checkly/headless-recorder#90]
When recording on chrome/edge(chromium) some pages halt and won't respond.
Not sure exactly why it happens but it seem to happen on pages that are ajax based rather than static.
given enough time it sometimes is able to record without crashing the page

the vertical "..." menu at https://www.youtube.com/feed/history halts the page but after a while records the action
the X for "Remove from watch history" at https://www.youtube.com/feed/history halts the page completely and is not being recorded
all this while https://www.youtube.com/ seem to be recording fine

The entire page also is very slow and clunky when using the extension

**Comment by tnolet** [comment]
@YoraiLevi I can't reproduce this on Chrome. Please just use Chrome and not Chrome/edge as this extension is not tested on that.

**Comment by YoraiLevi** [comment]
This was tested on chrome and edge(chromium) as noted by the / and brackets.
Tested again it is halting the entire page on my system.
Chrome Screen recording (recorded via window's Game Bar)
Pressed start to puppeteer record(context menu doesn't show up in video)
Pressed "X" to remove video
X is being pressed constantly
trying to interact with the page by pressing on "..." and on random places/links
no response.
"X" is still being 'pressed'
Stops puppeteer recording.
[(4) YouTube - Google Chrome 2020-07-03 01-39-30.zip](https://github.com/checkly/puppeteer-recorder/files/4866927/4.YouTube.-.Google.Chrome.2020-07-03.01-39-30.zip)
code generated after stopping the recording.
```js
const puppeteer = require('puppeteer');
const browser = await puppeteer.launch({ headless: false })
const page = await browser.newPage()
await page.goto('https://www.youtube.com/feed/history')

await page.setViewport({ width: 1676, height: 833 })

await browser.close()
```
after a while this message pops up
![image](https://user-images.githubusercontent.com/50873841/86414956-3794b980-bcce-11ea-9b68-0a64af059afa.png)
if ignore for a long while it disappears and the page continues with all the intended actions being performed.
![image](https://user-images.githubusercontent.com/50873841/86415402-97d82b00-bccf-11ea-913d-77fb7f8084b1.png)

This happen in multiple sites with similar non static button interactions.

**Comment by tnolet** [comment]
@YoraiLevi Thanks for reproducing, I' reopening as I think I can reproduce now too. I've honestly never ever seen this behaviour before. I do not have a solution for this so a patch or analysis would be appreciated.

**Comment by ianaya89** [comment]
https://github.com/checkly/headless-recorder/issues/232
